apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/part-of: nc-learners
  annotations:
    prometheus.io/port: "metrics-port"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      name: metrics-port
      port: 80
      targetPort: 8080
  type: LoadBalancer
