global:
  scrape_interval: 15s

rule_files:
  - /kubernetes/alert_rules.yaml

scrape_configs:
  - job_name: 'backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['nc-learners:80']
