apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nc-learners-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend-85fbcfcf96-scfwp
  endpoints:
    - interval: 10s
      port: metrics-port
      scrapeTimeout: 9s
  namespaceSelector:
    matchNames:
      - default
  