apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nc-learners-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: backend-85fbcfcf96-qf8d9
  endpoints:
    - interval: 10s
      port: metrics-port
      scrapeTimeout: 9s
  namespaceSelector:
    matchNames:
      - default
  